# Site settings
title: Electronic Sonnec
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Futurist poem #18 written by Beto O'Byrne and edited by Meropi Peponides. Code available at https://github.com/anirudh-eka/electronic_sonnec
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://toomanynames.com/electronic_sonnec" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
